trigger:
  branches:
    include: [main, master, tests]
  tags:
    include: ["*"]
  name: $(Date:yyyyMMdd)$(Rev:.r)
  jobs:
    - job: pytest
    pool:
      vmImage: Ubuntu-16.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.9.8
        displayName: Install Python
      - script: |
          python -m pip install -U pip
          pip install poetry
          poetry install
        displayName: Install dependences
      - script: |
          poetry run python -m pytest
        displayName: Test software